#!/usr/bin/env bash
# Install nginx and start it
apt-get -y install nginx
service nginx start
ufw allow 'Nginx HTTP'
echo "Hello World!\n" | sudo tee /var/127.0.0.1/html/index.nginx-debian.html
service nginx restart
